# Site settings
course_name: Astrofísica Estelar
# course_description: "Página para el curso Astrofísica Estelar del pregrado de Astronomía de la Universidad de Antioquia, Colombia."
course_semester: "Página para el curso Astrofísica Estelar del pregrado de Astronomía de la Universidad de Antioquia, Colombia."

baseurl: "/paginaEstelar" # the subpath of your site, e.g. /blog/
url: "http://esilvavilla.github.io/" # the base hostname & protocol for your site

schoolname: "Universidad de Antioquia"
schoolurl: "https://udea.edu.co"
# twitter_username: username 

address: |
    Universidad de Antioquia
    Calle 67 No. 53-108 Oficina 6-105
    050010, Medellín
    Colombia

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
google_analytics: G-PLT32NT5BN

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
